### ISSUE TITLE
Create a functionality for the users to search for bikes which can be borrowed.

### ISSUE THREAD

**Issue by Akash-M** [Akash-M/sap-ui5-frontend#7]

**Comment by Prateek057** [comment]
Features/Views/Components to be implemented

Output: 
1. Map
2. Search Bar

Functionalities: 
1. Search location
2. Search own position
3. Refresh
4. Recent Searches: List last searches

![searchbike-page](https://cloud.githubusercontent.com/assets/5918037/20488977/42cae25a-b009-11e6-8516-496f47d3e9f1.jpg)
